apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: akshakp/product-service:1.1.0-SNAPSHOT
        ports:
          - containerPort: 8080
        env:
        - name: POSTGRES_DB
          value: products_db
        - name: POSTGRES_USER
          value: dbuser
        - name: POSTGRES_PASSWORD
          value: password